#controllers:
#    resource: ../src/Controller/
#    type: attribute
index:
    prefix: "/"
    type: annotation
    resource: "../src/Controller/"
api:
    prefix: "/api"
    type: attribute
    resource: "../src/Controller/Api/"


